= ShiftedLCD Library for Arduino =

Allows communication via SPI Bus with alphanumerical liquid crystal displays (LCDs). 
This library works with LCD displays that are modified to use 595 Shift Register (in this case 74HC595) pin compatible. 
You can easily add Shift Register to your LCD. Please refer below link for pinouts and modifing your LCD.

For more information about this library please visit us at
http://github.com/omersiar/ShiftedLCD

== License ==

Copyright (C) 2006-2008 Hans-Christoph Steiner. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
